direction: right

SHACL -> Graph : constains

Frame -> SHACL : as described by
SPARQL -> SHACL : as described by 

ShIC -> SHACL : references  the shape file
ShIC -> SPARQL : references the query
ShIC -> Frame : reference the frame files
ShIC -> Principles : makes connections with
ShIC -> Vocabularies : expresses those offered

