direction: right

dg: data graph
scl: SHACL (SPARQL)
js: JSON Schema
fr: JSON-LD Frame
vm: Vocabulary Mapping

vr: Validation Report
fdg: Framed Data Graph
app: Application

dg -> scl -> vr
dg-> js -> vr
dg -> fr -> fdg -> app
dg -> vm
